---
name: Go

on:
  pull_request:

jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Lint
        run: |
          make dev/install/dep
          make test/lint

      - name: Test
        run: make test

      - name: Build
        run: make build/cmd/protolint

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Test
        run: go test -v -p 2 -count 1 -timeout 240s -race ./...
